# Generated by Django 2.2.5 on 2021-01-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cpation',
            new_name='caption',
        ),
    ]
